### ISSUE TITLE
Docker availability

### ISSUE THREAD

**Issue by lordraiden** [crowdsecurity/cs-whm-plugin#9]
It's possible to use this with the official docker containers or it will be in a future?

**Comment by LaurenceJJones** [comment]
> It's possible to use this with the official docker containers or it will be in a future?

Hi 👋🏻 

Do you mean install this within a cPanel docker container or interact with a Security Engine within docker?

**Comment by lordraiden** [comment]
> > It's possible to use this with the official docker containers or it will be in a future?
> 
> Hi 👋🏻
> 
> Do you mean install this within a cPanel docker container or interact with a Security Engine within docker?

Sorry my mistake, I thought it was a new web ui to admintrate crowdsec. I understand now that this is no the purpose of this project

**Comment by LaurenceJJones** [comment]
> > > It's possible to use this with the official docker containers or it will be in a future?
> > 
> > 
> > Hi 👋🏻
> > Do you mean install this within a cPanel docker container or interact with a Security Engine within docker?
> 
> Sorry my mistake, I thought it was a new web ui to admintrate crowdsec. I understand now that this is no the purpose of this project

I understand, I will close this as completed

**Comment by rr404** [comment]
Hello @lordraiden,
If I understand correcly, your WHM/Cpanel is installed on you server directly but you're using CrowdSec within a container right ?

In that case it complicates things and for now the plugin doesn't support that.
The reason is that we can't easily access the crowdsec CLI from the plugin if CrowdSec is in a container. It would be doable if both WHM/CPANEL and CrowdSec were in containers on the same docker network.

We could try to add an option to go through a docker exec and see if it works.
Are you currently using crowdsec along your WHM ?
Are you also using the [WHM collection](https://app.crowdsec.net/hub/author/crowdsecurity/collections/whm) ?
